"""Generate the Akandel shop page styles and add-to-cart experience views,
plus the matching Website Builder metadata.

Usage: python3 tools/gen_shop_cart.py <module root>
"""
import json
import os
import sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else '.'

SHOP_STYLES = [
    ('clean', 'Clean Cards'), ('minimal', 'Minimal Grid'), ('soft', 'Soft Shadow'),
    ('catalog', 'Bordered Catalog'), ('gallery', 'Image Gallery'), ('boutique', 'Boutique Centered'),
    ('dark', 'Dark Store'), ('pastel', 'Pastel Tiles'), ('dense', 'Compact Dense'),
    ('magazine', 'Magazine'), ('rounded', 'Rounded Pills'), ('panels', 'Sidebar Panels'),
    ('filterbar', 'Filter Bar'), ('band', 'Colored Header Band'), ('luxe', 'Gold Luxe'),
    ('accent', 'Blue Accent'), ('outline', 'Outline Hover'), ('floating', 'Floating Toolbar'),
    ('zoom', 'Zoom Focus'), ('showcase', 'Tall Showcase'), ('lined', 'Lined List'),
    ('glass', 'Glass Cards'), ('gradient', 'Gradient Header'), ('material', 'Material Elevation'),
]

# (key, name, panel type, content mode)
CART_STYLES = [
    ('drawer', 'Side Drawer', 'drawer-right', 'full'),
    ('drawer_minimal', 'Minimal Drawer', 'drawer-right', 'full'),
    ('drawer_left', 'Left Drawer', 'drawer-left', 'full'),
    ('drawer_dark', 'Dark Drawer', 'drawer-right', 'full'),
    ('drawer_wide', 'Wide Drawer + Picks', 'drawer-right', 'full'),
    ('drawer_floating', 'Floating Drawer', 'drawer-right', 'full'),
    ('drawer_glass', 'Glass Drawer', 'drawer-right', 'full'),
    ('drawer_gold', 'Gold Accent Drawer', 'drawer-right', 'full'),
    ('drawer_compact', 'Compact Drawer', 'drawer-right', 'full'),
    ('drawer_steps', 'Drawer with Steps', 'drawer-right', 'full'),
    ('sheet', 'Bottom Sheet', 'sheet', 'full'),
    ('sheet_dark', 'Dark Bottom Sheet', 'sheet', 'full'),
    ('modal', 'Centered Modal', 'modal', 'added'),
    ('modal_split', 'Split Modal', 'modal', 'added'),
    ('modal_success', 'Success Modal', 'modal', 'added'),
    ('fullscreen', 'Fullscreen Overlay', 'fullscreen', 'full'),
    ('dropdown', 'Mini Cart Dropdown', 'dropdown', 'full'),
    ('topbar', 'Top Bar Slide-down', 'topbar', 'added'),
    ('toast', 'Toast Card', 'toast-tr', 'added'),
    ('toast_bottom', 'Toast Bottom Left', 'toast-bl', 'added'),
    ('snackbar', 'Dark Snackbar', 'toast-bc', 'added'),
    ('pill', 'Floating Pill', 'toast-bc', 'added'),
    ('floating', 'Floating Mini Cart', 'floating', 'added'),
    ('bubble', 'Cart Bubble Pop', 'floating', 'added'),
]


def esc(s):
    return s.replace('&', '&amp;')


shop = ['<?xml version="1.0" encoding="utf-8"?>', '<odoo>', '',
        '<!-- Akandel shop page styles (generated by tools/gen_shop_cart.py). One active at a time,',
        '     selected in Website Builder > Products Page > Shop Style. -->']
for i, (key, name) in enumerate(SHOP_STYLES, 1):
    shop.append(f'''
<template id="ak_shop_style_{key}" inherit_id="website_sale.products" name="Akandel Shop Style {i:02d}: {esc(name)}" active="False">
    <xpath expr="//div[@id='o_wsale_container']" position="attributes">
        <attribute name="t-attf-class" add="ak-shop ak-shop-{key}" separator=" "/>
    </xpath>
</template>''')
shop.append('\n</odoo>\n')
open(os.path.join(ROOT, 'views/shop/shop_styles.xml'), 'w').write('\n'.join(shop))

cart = ['<?xml version="1.0" encoding="utf-8"?>', '<odoo>', '',
        '<!-- Akandel add-to-cart experiences (generated by tools/gen_shop_cart.py). One active at a',
        '     time, selected in Website Builder > Products Page / Product Page > Add to Cart Style. -->']
for i, (key, name, ptype, mode) in enumerate(CART_STYLES, 1):
    cart.append(f'''
<template id="ak_cart_style_{key}" inherit_id="website.layout" name="Akandel Cart Style {i:02d}: {esc(name)}" active="False">
    <xpath expr="//div[@id='wrapwrap']" position="attributes">
        <attribute name="data-ak-cart-style">{key}</attribute>
        <attribute name="data-ak-cart-type">{ptype}</attribute>
        <attribute name="data-ak-cart-mode">{mode}</attribute>
    </xpath>
</template>''')
cart.append('\n</odoo>\n')
open(os.path.join(ROOT, 'views/shop/cart_styles.xml'), 'w').write('\n'.join(cart))

meta = {
    'shop': [{'key': k, 'title': f'{i:02d} · {n}', 'view': f'theme_akandel.ak_shop_style_{k}'}
             for i, (k, n) in enumerate(SHOP_STYLES, 1)],
    'cart': [{'key': k, 'title': f'{i:02d} · {n}', 'view': f'theme_akandel.ak_cart_style_{k}', 'type': t}
             for i, (k, n, t, _m) in enumerate(CART_STYLES, 1)],
}
open(os.path.join(ROOT, 'static/src/builder/akandel_shop_designs.js'), 'w').write(
    '// Generated by tools/gen_shop_cart.py: keep in sync with views/shop/*_styles.xml\n'
    f'export const AKANDEL_SHOP_DESIGNS = {json.dumps(meta, indent=4)};\n')
print('ok', len(SHOP_STYLES), len(CART_STYLES))
